import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { CssBaseline, ThemeProvider } from "@mui/material";
import theme from "./components/Theme";
import DrawerAppBar from "./components/AppBar";
import SettingsProvider from "./contexts/SettingsContext";
import ThemeSettings from "./components/settings/index";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <CssBaseline />
      <AppRouterCacheProvider options={{ enableCssLayer: true }}>
        <ThemeProvider theme={theme}>
          <SettingsProvider>
            <ThemeSettings>
              <body className={inter.className}>

                <DrawerAppBar />
                {children}

              </body>
            </ThemeSettings>
          </SettingsProvider>
        </ThemeProvider>
      </AppRouterCacheProvider>
    </html>
  );
}
